sudo: required
services:
  - docker

before_install:
  - docker build -t ibarashkov/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run ibarashkov/react-test npm test -- --coverage

after_success:
  - docker build -t ibarashkov/multi-client ./client
  - docker build -t ibarashkov/multi-nginx ./nginx
  - docker build -t ibarashkov/multi-server ./server
  - docker build -t ibarashkov/multi-worker ./worker
  - echo $DOCKER_PASSWORD | docker login -u $DOCKER_ID --password-stdin
  - docker push ibarashkov/multi-client
  - docker push ibarashkov/multi-nginx
  - docker push ibarashkov/multi-server
  - docker push ibarashkov/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-694331572757
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
